# Generated by Django 2.0.7 on 2018-07-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('radius', models.IntegerField()),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('distance', models.IntegerField()),
                ('balanced', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alkanza.Evaluation')),
            ],
        ),
    ]
